#sdk: "/Users/lars/.rvm/gems/ruby-1.8.7-p357/gems/rhodes-3.3.2.beta.4"
sdkversion: 3.3.2
name: metademo1
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.metademo1
  BundleURLScheme: metademo1
wp:
  productid: '93ca9c00-33c1-012f-269f-482a141043d9'
symbian:
  uid: '0xe6697df5'
android:
  version: 2.1
extensions:
  - json
  - rhodes_translator
  - mspec
  - fileutils

